export { default as Homework1 } from './Homework1/Homework1'
export { default as Homework2 } from './Homework2/Homework2'
export { default as Homework3 } from './Homework3/Homework3'
export { default as Homework4 } from './Homework4/Homework4'
export { default as Homework5 } from './Homework5/Homework5'
export { default as Homework6 } from './Homework6/Homework6'